<?php

define("_ACCUEIL","Home");
define("_PAYS","Country");
define("_LANGUE","Languages");
define("_DOMAINES","Field");
define("_CONNECTER","Log in");
define("_PROFIL","Profile");
define("_FORMULAIRE","Form");
define("_DECONNEXION","Log out");
define("_CONTACT","Contact");

//ARTICLES

define("_VISITE","Visit");
define("_PRATIQUE","Useful");
define("_CULTURE","Cultur");

define("_MONT","Must-sees in Montreal");
define("_MONTDESC","Soon visiting Montreal and you do not know what to do? Check out this article.");

define("_BOBIGNY","Bobigny IUT");
define("_BOBIGNYDESC","Presentation of Bobigny's IUT");

define("_NY","Must-sees in NY");
define("_NYDESC","Must-see things to see in NY. You will be able to discover the best places there. By going through the Brooklyn Bridge and Rockefeller.");


define("_VALISE","Prepare your suitcase");
define("_VALISEDESC","How to prepare your suitcase for your studies?");


define("_UQAC","UQAC");
define("_UQACDESC","Come and discover UQAC, a dreamy Quebec establishment!");


define("_FROID","Prepare for the cold");
define("_FROIDDESC","If you are going to study in Canada, you will need a lot of advice as to which coat to choose.");


define("_P13","Paris 13");
define("_P13DESC","Discover the testimony of Lucie, a student at Paris 13 University");


define("_RS","Social networks");
define("_ANNEXE","Annex");
define("_ABOUT","About");
define("_ML","Legal notice");
define("_PARTNER","Partner");



?>