<?php

define("_ACCUEIL","Accueil");
define("_PAYS","Pays");
define("_LANGUE","Langues");
define("_DOMAINES","Domaines");
define("_CONNECTER","Se connecter");
define("_PROFIL","Profil");
define("_FORMULAIRE","Formulaire");
define("_DECONNEXION","Déconnexion");
define("_CONTACT","Contact");

//ARTICLES

define("_VISITE","Visites");
define("_PRATIQUE","Pratique");
define("_CULTURE","Culture");

define("_MONT","Incontournables à Montréal");
define("_MONTDESC","Bientôt en visite de Montréal et vous ne savez pas quoi faire ? Consultez cet article.");

define("_BOBIGNY","IUT de Bobigny");
define("_BOBIGNYDESC","Présentation de l'IUT de Bobigny");

define("_NY","Incontournables à New York");
define("_NYDESC","Choses incontournables à voir à NY. Vous allez pouvoir découvrir les meilleurs endroits qui s'y trouvent.En passant par le Brooklyn Bridge et Rockfeller.");


define("_VALISE","Préparer sa valise");
define("_VALISEDESC","Comment préparer sa valise pour ses études ?");


define("_UQAC","UQAC");
define("_UQACDESC","Venez découvrir l'UQAC, établissement québecois de rêve !");


define("_FROID","Se préparer au froid");
define("_FROIDDESC","Si vous partez étudier au Canada, vous aurez besoin de beaucoup de conseil quant à savoir quel manteau choisir.");


define("_P13","Paris 13");
define("_P13DESC","Découvrez le témoignage de Lucie, étudiante à l'Université Paris 13");


define("_RS","Réseaux sociaux");
define("_ANNEXE","Annexes");
define("_ABOUT","À propos");
define("_ML","Mentions légales");
define("_PARTNER","Partenaires");



?>
